FROM ubuntu

RUN apt update

RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash 
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install 16
RUN . "$NVM_DIR/nvm.sh" && nvm install 20

RUN apt install node-typescript -y

