FROM ubuntu

RUN apt update
RUN apt install -y git
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
#  source ~/.bashrc && \
#  nvm install node && \
RUN apt install node-typescript -y
