# FROM  openjdk:17-oracle


# # RUN yum install -y java-17-openjdk-devel
# RUN microdnf  update
# RUN microdnf  install -y git
# RUN microdnf  install -y maven
# RUN microdnf  install -y nodejs
# RUN microdnf  install -y npm

# FROM debian

# RUN apt-get update
# RUN apt-get install -y openjdk-17-jdk
# RUN apt-get install -y git
# RUN apt-get  install -y maven
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash \
#     && nvm install 
# # RUN bash nvm install 
# # RUN apt-get  install -y nodejs npm
# RUN apt-get install -y build-essential
# # RUN apt-get  install -y npm

FROM redhat/ubi9
RUN yum install -y java-1.8.0-openjdk-devel
RUN yum install -y java-17-openjdk-devel
RUN yum update
RUN yum install -y git
RUN yum install -y maven
RUN yum install -y nodejs
RUN yum install -y npm