# FROM python
# RUN apt-get -y update
# RUN apt-get -y install git

FROM redhat/ubi9

RUN yum update
RUN yum install -y git
RUN yum install -y python3
RUN yum install -y python3-pytest
RUN yum install -y python3-pip
RUN pip install -U ipykernal